[HOT-39] Add colour related attributes for categories
RedDragonSquad/Hotpot-Buddy pull request #29
Opened 2022-09-16 00:09 UTC by Keerush

JIRA: https://hotpotbuddy.atlassian.net/browse/HOT-39

Added color palettes for each category. As a default is the miscellaneous colors if no category matches or is missing.

2022-09-16 15:50 UTC, AndrewLin95 reviewed
Looks pretty good!!!

2022-09-16 15:50 UTC, AndrewLin95 commented on client/src/utils/colors.tsx
> +      'AA000'
This one looks kinda off `'AA000'`

2022-09-16 15:50 UTC, AndrewLin95 commented on client/src/utils/colors.tsx
> +const CATEGORY_COLORS = new Map([
Oh missing the "#" from these.

2022-09-16 15:52 UTC, AndrewLin95 requested changes
Updated to request changes. Almost missed the "#"'s you mentioned in chat myself.

2022-09-17 00:28 UTC, Keerush commented on client/src/utils/colors.tsx
> +const CATEGORY_COLORS = new Map([
Yep, done.

2022-09-17 00:32 UTC, Keerush commented on client/src/utils/colors.tsx
> +      'AA000'
Nice catch, missed a 0

2022-09-17 16:33 UTC, AndrewLin95 approved these changes
:shipit:

2022-09-17 16:34 UTC, merged